import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export interface InternshipData {
  id: string;
  title: string;
  company: string;
  location: string;
  type: "remote" | "on-site" | "hybrid";
  duration: string;
  stipend?: string;
  category: "paid" | "unpaid" | "stipend";
  domain: string;
  companyType: "government" | "private" | "startup" | "ngo";
  verificationStatus: "verified" | "warning" | "unverified";
  trustScore: number;
  applicants: number;
  views: number;
  postedDate: string;
  deadline: string;
  description: string;
  fullDescription?: string;
  skills?: string[];
  responsibilities?: string[];
  perks?: string[];
  eligibility?: string;
  logoUrl?: string;
  website?: string;
  recruiterEmail?: string;
}

export const VerificationStatus = {
  VERIFIED: "verified",
  WARNING: "warning",
  UNVERIFIED: "unverified",
} as const;

// Curated, realistic-feeling catalog. 24 entries so the page genuinely has
// "more internships" once you scroll past the first batch.
export const INTERNSHIPS_CATALOG: InternshipData[] = [
  {
    id: "1",
    title: "Software Development Intern",
    company: "TechCorp Solutions",
    location: "Bangalore, India",
    type: "hybrid",
    duration: "3 months",
    stipend: "₹15,000/month",
    category: "paid",
    domain: "Technology",
    companyType: "private",
    verificationStatus: "verified",
    trustScore: 95,
    applicants: 234,
    views: 1520,
    postedDate: "2 days ago",
    deadline: "Jul 15, 2026",
    description:
      "Join our dynamic team to work on cutting-edge web applications using React and Node.js. Great learning opportunity with mentorship.",
    fullDescription:
      "TechCorp Solutions is looking for a curious and driven Software Development Intern to join our platform team. You will pair with senior engineers to build features used by millions of users, contribute to internal tooling, and participate in architecture reviews.",
    skills: ["React", "TypeScript", "Node.js", "Git", "REST APIs"],
    responsibilities: [
      "Build and ship features end-to-end in our React + Node.js stack",
      "Write clean, well-tested code with peer reviews",
      "Collaborate with designers and product managers in a scrum cadence",
    ],
    perks: [
      "Mentorship from senior engineers",
      "Flexible hybrid schedule (3 days office)",
      "Letter of recommendation on successful completion",
    ],
    eligibility: "Pursuing B.Tech / B.E. in CS or related, 2026–2028 batch",
    website: "https://example.com/techcorp",
    recruiterEmail: "careers@techcorp.example",
  },
  {
    id: "2",
    title: "Data Science Intern",
    company: "AI Innovations",
    location: "Remote",
    type: "remote",
    duration: "6 months",
    stipend: "₹20,000/month",
    category: "paid",
    domain: "Data Science",
    companyType: "startup",
    verificationStatus: "verified",
    trustScore: 92,
    applicants: 189,
    views: 987,
    postedDate: "1 day ago",
    deadline: "Jul 20, 2026",
    description:
      "Work on real-world ML projects, analyze large datasets, and contribute to AI model development. Python and statistics knowledge required.",
    fullDescription:
      "AI Innovations works with enterprise clients to deploy ML solutions in production. As a Data Science Intern you will own a discrete sub-project, ship a model into a staging environment, and present findings to a non-technical client audience.",
    skills: ["Python", "pandas", "scikit-learn", "SQL", "statistics"],
    responsibilities: [
      "Explore and clean real customer datasets",
      "Train and evaluate baseline + advanced ML models",
      "Summarise results in clear, visual reports",
    ],
    perks: [
      "Fully remote with flexible hours",
      "GPU credits for personal projects",
      "PPO opportunity based on performance",
    ],
    eligibility: "Strong Python + statistics fundamentals; prior Kaggle work a plus",
    recruiterEmail: "ds-team@aiinnovations.example",
  },
  {
    id: "3",
    title: "Digital Marketing Intern",
    company: "Growth Agency",
    location: "Mumbai, India",
    type: "on-site",
    duration: "2 months",
    stipend: "₹8,000/month",
    category: "stipend",
    domain: "Marketing",
    companyType: "private",
    verificationStatus: "warning",
    trustScore: 75,
    applicants: 156,
    views: 743,
    postedDate: "3 days ago",
    deadline: "Jul 10, 2026",
    description:
      "Learn digital marketing strategies, SEO, social media marketing, and content creation. Perfect for beginners looking to start their career.",
    fullDescription:
      "You'll shadow our growth marketers on live client campaigns. Expect to write copy, set up Meta ads, and report on weekly performance. Note: This listing is currently under caution — we recommend confirming the recruiter's identity by email before sharing personal details.",
    skills: ["Social media", "Canva", "Copywriting", "Basic SEO"],
    responsibilities: [
      "Draft weekly content calendars for 2 client brands",
      "Set up and monitor paid campaigns on Meta Ads Manager",
      "Track KPIs in our shared Looker Studio dashboard",
    ],
    perks: ["Stipend + performance bonus", "In-office snacks & lunch"],
    eligibility: "Any graduate / final-year student with strong written English",
    recruiterEmail: "hr@growthagency.example",
  },
  {
    id: "4",
    title: "Research Intern",
    company: "Government Research Lab",
    location: "Delhi, India",
    type: "on-site",
    duration: "4 months",
    category: "unpaid",
    domain: "Research",
    companyType: "government",
    verificationStatus: "verified",
    trustScore: 98,
    applicants: 89,
    views: 456,
    postedDate: "5 days ago",
    deadline: "Jul 25, 2026",
    description:
      "Contribute to groundbreaking research in renewable energy. Work with senior scientists and gain valuable research experience.",
    fullDescription:
      "Join a national-lab project investigating next-gen solar cell materials. You will assist with lab experiments, run simulations in MATLAB, and co-author a research paper for an IEEE conference.",
    skills: ["Materials science basics", "MATLAB", "Technical writing"],
    responsibilities: [
      "Prepare samples and run characterization experiments",
      "Simulate optical properties in MATLAB",
      "Document findings in shared research notes",
    ],
    perks: ["Publication co-authorship", "Lab access + mentor pairing", "Certificate"],
    eligibility: "M.Sc. / B.Tech final year, materials/EEE/Physics background",
    recruiterEmail: "research@govlab.example",
  },
  {
    id: "5",
    title: "UI/UX Design Intern",
    company: "Design Studios",
    location: "Remote",
    type: "remote",
    duration: "3 months",
    stipend: "₹12,000/month",
    category: "paid",
    domain: "Design",
    companyType: "startup",
    verificationStatus: "unverified",
    trustScore: 65,
    applicants: 267,
    views: 1234,
    postedDate: "1 week ago",
    deadline: "Jul 5, 2026",
    description:
      "Create user-centered designs for mobile and web applications. Portfolio required. Figma and Adobe XD experience preferred.",
    fullDescription:
      "Design Studios runs design sprints for early-stage SaaS founders. As a UI/UX Intern you will own 2–3 small product redesigns end-to-end, present to founders, and iterate on feedback.",
    skills: ["Figma", "Wireframing", "User research", "Prototyping"],
    responsibilities: [
      "Run lightweight user interviews (3–5 per project)",
      "Produce wireframes → high-fidelity mockups",
      "Hand off specs to engineers with annotated frames",
    ],
    perks: ["Fully remote", "Portfolio-worthy projects", "Letter of recommendation"],
    eligibility: "Portfolio with at least 2 case studies required",
    recruiterEmail: "design-jobs@designstudios.example",
  },
  {
    id: "6",
    title: "Finance Analyst Intern",
    company: "Investment Bank Corp",
    location: "Mumbai, India",
    type: "on-site",
    duration: "6 months",
    stipend: "₹25,000/month",
    category: "paid",
    domain: "Finance",
    companyType: "private",
    verificationStatus: "verified",
    trustScore: 96,
    applicants: 145,
    views: 892,
    postedDate: "4 days ago",
    deadline: "Jul 18, 2026",
    description:
      "Assist in financial modeling, market research, and investment analysis. Excel proficiency and finance knowledge required.",
    fullDescription:
      "Work alongside our M&A team on live deals. You'll build comps, prepare pitch decks, and support senior bankers in client meetings.",
    skills: ["Excel (advanced)", "Financial modeling", "PowerPoint", "Bloomberg basics"],
    responsibilities: [
      "Build comparable company analyses",
      "Maintain deal databases in Excel + Bloomberg",
      "Draft sections of client pitch decks",
    ],
    perks: ["High stipend", "Pre-placement interview track", "Networking with senior bankers"],
    eligibility: "MBA / final-year BBA / CA intermediate; finance background required",
    recruiterEmail: "careers@investmentbank.example",
  },
  {
    id: "7",
    title: "Content Writing Intern",
    company: "BrightMinds NGO",
    location: "Remote",
    type: "remote",
    duration: "3 months",
    category: "unpaid",
    domain: "Marketing",
    companyType: "ngo",
    verificationStatus: "verified",
    trustScore: 88,
    applicants: 78,
    views: 320,
    postedDate: "6 days ago",
    deadline: "Aug 2, 2026",
    description:
      "Write compelling stories for our non-profit campaigns. Strong written English and a passion for social impact required.",
    fullDescription:
      "BrightMinds runs literacy campaigns in rural India. You'll write 4 long-form stories per month plus weekly social posts. Great portfolio-builder if you care about impact work.",
    skills: ["Storytelling", "Editing", "SEO basics"],
    responsibilities: [
      "Interview beneficiaries and draft feature stories",
      "Edit submitted pieces from regional writers",
      "Repurpose long-form into social posts",
    ],
    perks: ["Verified NGO certificate", "Featured byline on published pieces"],
    eligibility: "Strong written English; journalism / literature background a plus",
    recruiterEmail: "stories@brightminds.example",
  },
  {
    id: "8",
    title: "Frontend Engineering Intern",
    company: "PixelForge Labs",
    location: "Pune, India",
    type: "hybrid",
    duration: "4 months",
    stipend: "₹18,000/month",
    category: "paid",
    domain: "Technology",
    companyType: "startup",
    verificationStatus: "verified",
    trustScore: 91,
    applicants: 312,
    views: 1102,
    postedDate: "1 day ago",
    deadline: "Jul 28, 2026",
    description:
      "Build modern React UIs for our design-tooling product. Strong JavaScript fundamentals and eye for detail required.",
    fullDescription:
      "PixelForge is a 30-person design-tooling startup. As a Frontend Intern you'll own UI features in our Figma-style canvas editor — performance-sensitive code with real users from day one.",
    skills: ["React", "TypeScript", "CSS / Tailwind", "Canvas APIs"],
    responsibilities: [
      "Ship product features in our React + TypeScript codebase",
      "Optimise rendering for our canvas-based editor",
      "Write unit tests with React Testing Library",
    ],
    perks: ["Hybrid (2 days office)", "Latest hardware", "PPO track"],
    eligibility: "Solid JS fundamentals; React experience preferred",
    recruiterEmail: "frontend@pixelforge.example",
  },
  {
    id: "9",
    title: "Backend Engineering Intern",
    company: "CloudStack Systems",
    location: "Hyderabad, India",
    type: "on-site",
    duration: "6 months",
    stipend: "₹22,000/month",
    category: "paid",
    domain: "Technology",
    companyType: "private",
    verificationStatus: "verified",
    trustScore: 94,
    applicants: 198,
    views: 1043,
    postedDate: "3 days ago",
    deadline: "Aug 5, 2026",
    description:
      "Work on distributed systems powering our cloud platform. Java / Go experience preferred.",
    fullDescription:
      "You'll join the team responsible for our multi-region control plane. Expect to write production Go, design gRPC APIs, and contribute to SRE on-call rotations (with senior backup).",
    skills: ["Java or Go", "Distributed systems", "Linux", "SQL"],
    responsibilities: [
      "Implement new APIs in our Go services",
      "Add observability with Prometheus + Grafana",
      "Participate in design reviews",
    ],
    perks: ["Pre-placement offer track", "Free meals", "Relocation support"],
    eligibility: "B.Tech CS 2026 / 2027 batch with strong fundamentals",
    recruiterEmail: "careers@cloudstack.example",
  },
  {
    id: "10",
    title: "Mobile App Developer Intern",
    company: "AppVenture Studio",
    location: "Remote",
    type: "remote",
    duration: "3 months",
    stipend: "₹14,000/month",
    category: "paid",
    domain: "Technology",
    companyType: "startup",
    verificationStatus: "verified",
    trustScore: 89,
    applicants: 167,
    views: 712,
    postedDate: "4 days ago",
    deadline: "Jul 22, 2026",
    description:
      "Build cross-platform mobile apps using React Native. Experience with iOS or Android SDKs a plus.",
    fullDescription:
      "Help us ship a React Native fitness app from MVP to beta. You'll work closely with a senior engineer and a designer, owning 2–3 user-facing screens.",
    skills: ["React Native", "JavaScript / TypeScript", "REST APIs"],
    responsibilities: [
      "Implement UI from Figma designs",
      "Wire up backend APIs and local state",
      "Write integration tests with Detox",
    ],
    perks: ["Remote-first", "Direct mentorship", "App-store credit on shipped features"],
    eligibility: "Comfort with React; mobile experience preferred",
    recruiterEmail: "mobile@appventure.example",
  },
  {
    id: "11",
    title: "Machine Learning Research Intern",
    company: "DeepVision AI",
    location: "Bangalore, India",
    type: "hybrid",
    duration: "6 months",
    stipend: "₹30,000/month",
    category: "paid",
    domain: "Data Science",
    companyType: "startup",
    verificationStatus: "verified",
    trustScore: 97,
    applicants: 421,
    views: 1789,
    postedDate: "2 days ago",
    deadline: "Aug 12, 2026",
    description:
      "Conduct applied ML research in computer vision. Strong PyTorch skills and publication experience preferred.",
    fullDescription:
      "DeepVision is an applied research lab building vision models for retail analytics. You'll prototype novel architectures, run ablation studies, and (ideally) submit to a top-tier conference.",
    skills: ["PyTorch", "Computer vision", "Research writing", "Linux"],
    responsibilities: [
      "Prototype and benchmark vision models",
      "Run ablations and write internal tech reports",
      "Co-author an external publication",
    ],
    perks: ["Top-of-market stipend", "GPU cluster access", "Publication support"],
    eligibility: "MS / PhD or B.Tech with strong research record",
    recruiterEmail: "research@deepvision.example",
  },
  {
    id: "12",
    title: "Product Management Intern",
    company: "SaaSCo",
    location: "Remote",
    type: "remote",
    duration: "3 months",
    stipend: "₹16,000/month",
    category: "paid",
    domain: "Technology",
    companyType: "startup",
    verificationStatus: "verified",
    trustScore: 90,
    applicants: 254,
    views: 981,
    postedDate: "5 days ago",
    deadline: "Jul 30, 2026",
    description:
      "Shadow our PM team, write PRDs, run user interviews, and own a small feature from discovery to launch.",
    fullDescription:
      "Ideal for someone curious about product-led growth. You'll write 1 PRD, run 5 user interviews, and present a launch retro at the end of the program.",
    skills: ["Written communication", "Basic analytics", "Curiosity"],
    responsibilities: [
      "Draft PRDs with input from senior PMs",
      "Run user interviews and synthesise themes",
      "Track launch metrics in Mixpanel",
    ],
    perks: ["Remote", "Direct PM mentorship", "PPO interview track"],
    eligibility: "Any final-year student with strong writing skills",
    recruiterEmail: "pm-jobs@saasco.example",
  },
  {
    id: "13",
    title: "Cybersecurity Analyst Intern",
    company: "SecureNet Solutions",
    location: "Bangalore, India",
    type: "on-site",
    duration: "4 months",
    stipend: "₹18,000/month",
    category: "paid",
    domain: "Technology",
    companyType: "private",
    verificationStatus: "verified",
    trustScore: 93,
    applicants: 132,
    views: 654,
    postedDate: "1 week ago",
    deadline: "Aug 1, 2026",
    description:
      "Assist our SOC team with monitoring, incident response, and threat hunting. Networking fundamentals required.",
    fullDescription:
      "Work alongside senior analysts in a 24×7 SOC. You'll triage alerts, write Splunk queries, and contribute to playbooks for new threat actors.",
    skills: ["Networking basics", "Linux", "Splunk / ELK", "OWASP Top 10"],
    responsibilities: [
      "Triage SIEM alerts in our 24×7 SOC",
      "Write Splunk queries to detect anomalies",
      "Document playbooks for recurring incidents",
    ],
    perks: ["Industry-recognised certificate", "Stipend", "SOC rotation"],
    eligibility: "B.Tech CS / IT 2026–2027; Security+ a plus",
    recruiterEmail: "soc-jobs@securenet.example",
  },
  {
    id: "14",
    title: "DevOps Engineering Intern",
    company: "InfraCloud Inc",
    location: "Pune, India",
    type: "hybrid",
    duration: "6 months",
    stipend: "₹20,000/month",
    category: "paid",
    domain: "Technology",
    companyType: "private",
    verificationStatus: "verified",
    trustScore: 92,
    applicants: 175,
    views: 803,
    postedDate: "6 days ago",
    deadline: "Aug 8, 2026",
    description:
      "Build CI/CD pipelines, manage Kubernetes clusters, and improve developer experience.",
    fullDescription:
      "You'll own CI/CD migrations for 3 internal services, write Terraform modules, and help us standardise on GitOps with ArgoCD.",
    skills: ["Kubernetes", "Docker", "Terraform", "GitHub Actions"],
    responsibilities: [
      "Migrate Jenkins pipelines to GitHub Actions",
      "Author Terraform modules for new AWS services",
      "Document onboarding runbooks",
    ],
    perks: ["Hybrid", "Cloud certifications reimbursed", "PPO track"],
    eligibility: "Hands-on experience with at least one CI tool",
    recruiterEmail: "devops@infracloud.example",
  },
  {
    id: "15",
    title: "Graphic Design Intern",
    company: "BrightWave Studios",
    location: "Mumbai, India",
    type: "on-site",
    duration: "3 months",
    stipend: "₹10,000/month",
    category: "stipend",
    domain: "Design",
    companyType: "startup",
    verificationStatus: "verified",
    trustScore: 86,
    applicants: 95,
    views: 412,
    postedDate: "2 days ago",
    deadline: "Jul 12, 2026",
    description:
      "Design social media creatives, brand collateral, and pitch decks for agency clients.",
    fullDescription:
      "BrightWave is a 12-person design agency. You'll work across 5 client accounts, primarily on social campaigns and pitch decks.",
    skills: ["Adobe Illustrator", "Photoshop", "Canva", "Typography"],
    responsibilities: [
      "Design weekly social media grids for 3 clients",
      "Build pitch deck templates",
      "Collaborate with copywriters on campaign concepts",
    ],
    perks: ["Studio environment", "Portfolio projects across industries"],
    eligibility: "Proficiency in Adobe suite required",
    recruiterEmail: "hello@brightwave.example",
  },
  {
    id: "16",
    title: "Business Development Intern",
    company: "NextWave Sales",
    location: "Gurgaon, India",
    type: "on-site",
    duration: "3 months",
    stipend: "₹12,000/month",
    category: "stipend",
    domain: "Finance",
    companyType: "private",
    verificationStatus: "warning",
    trustScore: 72,
    applicants: 211,
    views: 587,
    postedDate: "4 days ago",
    deadline: "Jul 18, 2026",
    description:
      "Support the BD team with lead generation, outreach, and CRM hygiene. Confident spoken English required.",
    fullDescription:
      "You'll run cold-outreach campaigns on LinkedIn, qualify inbound leads, and keep our HubSpot CRM tidy. Note: this listing is currently under caution — verify the recruiter before paying any fees (we never charge applicants).",
    skills: ["Spoken English", "LinkedIn", "Excel", "CRM basics"],
    responsibilities: [
      "Source 50+ leads per week on LinkedIn",
      "Run first-touch email sequences",
      "Maintain CRM hygiene in HubSpot",
    ],
    perks: ["Stipend + uncapped commission", "Sales training"],
    eligibility: "Any graduate; prior SDR experience a plus",
    recruiterEmail: "bd@nextwave.example",
  },
  {
    id: "17",
    title: "AI Engineering Intern",
    company: "NeuralPath Labs",
    location: "Remote",
    type: "remote",
    duration: "4 months",
    stipend: "₹24,000/month",
    category: "paid",
    domain: "Data Science",
    companyType: "startup",
    verificationStatus: "verified",
    trustScore: 94,
    applicants: 287,
    views: 1320,
    postedDate: "3 days ago",
    deadline: "Aug 1, 2026",
    description:
      "Fine-tune LLMs and ship AI features into production. Strong Python + PyTorch required.",
    fullDescription:
      "You'll fine-tune open-source LLMs on customer datasets, build evaluation harnesses, and deploy inference endpoints behind a feature flag.",
    skills: ["Python", "PyTorch", "Hugging Face", "REST APIs"],
    responsibilities: [
      "Fine-tune LLMs on domain-specific data",
      "Build evaluation pipelines",
      "Ship behind feature flags in our inference service",
    ],
    perks: ["Top-of-market stipend", "Compute credits", "Conference budget"],
    eligibility: "Strong ML fundamentals; LLM coursework a strong plus",
    recruiterEmail: "ai-jobs@neuralpath.example",
  },
  {
    id: "18",
    title: "HR Operations Intern",
    company: "PeopleFirst Co",
    location: "Noida, India",
    type: "on-site",
    duration: "3 months",
    stipend: "₹9,000/month",
    category: "stipend",
    domain: "Finance",
    companyType: "private",
    verificationStatus: "verified",
    trustScore: 84,
    applicants: 142,
    views: 489,
    postedDate: "5 days ago",
    deadline: "Jul 14, 2026",
    description:
      "Support our People Ops team with onboarding, payroll inputs, and engagement programs.",
    fullDescription:
      "You'll help onboard 30+ new joiners each month, run engagement surveys, and assist the payroll team with data entry.",
    skills: ["MS Excel", "Communication", "Discretion"],
    responsibilities: [
      "Run weekly onboarding sessions",
      "Maintain employee data in HRIS",
      "Coordinate monthly engagement events",
    ],
    perks: ["People Ops exposure", "Stipend", "Letter of recommendation"],
    eligibility: "BBA / MBA HR students preferred",
    recruiterEmail: "people@peoplefirst.example",
  },
  {
    id: "19",
    title: "Mechanical Engineering Intern",
    company: "AutoDrive Manufacturing",
    location: "Chennai, India",
    type: "on-site",
    duration: "6 months",
    stipend: "₹12,000/month",
    category: "paid",
    domain: "Research",
    companyType: "private",
    verificationStatus: "verified",
    trustScore: 88,
    applicants: 76,
    views: 318,
    postedDate: "1 week ago",
    deadline: "Jul 25, 2026",
    description:
      "Work on CAD designs for our EV drivetrain line. SolidWorks / CATIA experience preferred.",
    fullDescription:
      "Join the EV drivetrain team. You'll assist senior designers with CAD models, run tolerance stack-ups, and prepare drawings for manufacturing.",
    skills: ["SolidWorks", "CATIA", "GD&T", "Mechanical drawings"],
    responsibilities: [
      "Update CAD models for the drivetrain subassembly",
      "Run tolerance and fit analyses",
      "Prepare manufacturing drawings with GD&T",
    ],
    perks: ["Factory floor exposure", "Stipend", "Tooling allowance"],
    eligibility: "B.E. Mechanical 2026 / 2027 batch",
    recruiterEmail: "mech-jobs@autodrive.example",
  },
  {
    id: "20",
    title: "Video Editor Intern",
    company: "ReelCraft Media",
    location: "Remote",
    type: "remote",
    duration: "3 months",
    stipend: "₹11,000/month",
    category: "paid",
    domain: "Design",
    companyType: "startup",
    verificationStatus: "verified",
    trustScore: 87,
    applicants: 198,
    views: 712,
    postedDate: "2 days ago",
    deadline: "Jul 19, 2026",
    description:
      "Edit short-form videos for our creator clients. Premiere Pro / DaVinci Resolve experience required.",
    fullDescription:
      "You'll edit 5–7 short-form videos per week for YouTube and Instagram creators, manage project files, and meet daily deadlines.",
    skills: ["Premiere Pro", "DaVinci Resolve", "Storytelling", "Sound design"],
    responsibilities: [
      "Edit 5–7 short-form videos weekly",
      "Add captions, transitions, and basic motion graphics",
      "Maintain organised project libraries",
    ],
    perks: ["Remote", "Build a real portfolio", "Direct mentor feedback"],
    eligibility: "Portfolio with at least 3 edited reels",
    recruiterEmail: "edits@reelcraft.example",
  },
  {
    id: "21",
    title: "Operations Intern",
    company: "LogiChain Co",
    location: "Mumbai, India",
    type: "on-site",
    duration: "3 months",
    stipend: "₹10,000/month",
    category: "stipend",
    domain: "Finance",
    companyType: "startup",
    verificationStatus: "verified",
    trustScore: 85,
    applicants: 113,
    views: 401,
    postedDate: "3 days ago",
    deadline: "Jul 24, 2026",
    description:
      "Help optimise last-mile delivery routes and run daily ops standups with our dispatch team.",
    fullDescription:
      "LogiChain operates same-day delivery in 6 cities. You'll analyse route efficiency, run dispatch standups, and propose operational improvements.",
    skills: ["Excel", "Analytical mindset", "Communication"],
    responsibilities: [
      "Analyse route efficiency from our dispatch dashboard",
      "Run daily ops standups with the dispatch team",
      "Pilot 1 process improvement over 3 months",
    ],
    perks: ["Operations exposure", "Stipend"],
    eligibility: "BBA / Engineering students with strong Excel skills",
    recruiterEmail: "ops@logichain.example",
  },
  {
    id: "22",
    title: "Cloud Architecture Intern",
    company: "SkyHigh Cloud",
    location: "Bangalore, India",
    type: "hybrid",
    duration: "6 months",
    stipend: "₹26,000/month",
    category: "paid",
    domain: "Technology",
    companyType: "private",
    verificationStatus: "verified",
    trustScore: 95,
    applicants: 184,
    views: 891,
    postedDate: "4 days ago",
    deadline: "Aug 6, 2026",
    description:
      "Design cloud-native architectures for enterprise clients. AWS knowledge preferred.",
    fullDescription:
      "Work alongside our solution architects on customer-facing design reviews. You'll produce architecture diagrams, estimate costs, and document best practices.",
    skills: ["AWS", "Networking", "Linux", "Terraform"],
    responsibilities: [
      "Draft architecture diagrams for client proposals",
      "Estimate AWS spend using the pricing calculator",
      "Maintain internal reference architectures",
    ],
    perks: ["AWS certification reimbursement", "Hybrid", "PPO track"],
    eligibility: "AWS Solutions Architect Associate a strong plus",
    recruiterEmail: "cloud-jobs@skyhigh.example",
  },
  {
    id: "23",
    title: "Social Media Manager Intern",
    company: "ViralHive Agency",
    location: "Remote",
    type: "remote",
    duration: "3 months",
    stipend: "₹9,000/month",
    category: "stipend",
    domain: "Marketing",
    companyType: "startup",
    verificationStatus: "warning",
    trustScore: 70,
    applicants: 245,
    views: 622,
    postedDate: "2 days ago",
    deadline: "Jul 11, 2026",
    description:
      "Run day-to-day social media for 4 D2C brands. Native English + Instagram Reels experience required.",
    fullDescription:
      "You'll own Instagram and LinkedIn calendars for 4 brands. Note: this listing is under caution — verify recruiter identity before sharing any IDs or fees.",
    skills: ["Instagram Reels", "Copywriting", "Canva"],
    responsibilities: [
      "Post daily Reels + Stories across 4 brand accounts",
      "Reply to DMs and moderate comments",
      "Share weekly analytics with founders",
    ],
    perks: ["Remote", "Performance bonus"],
    eligibility: "Portfolio of Reels with >10k views a strong plus",
    recruiterEmail: "social@viralhive.example",
  },
  {
    id: "24",
    title: "Public Policy Research Intern",
    company: "Civic Futures Foundation",
    location: "Delhi, India",
    type: "on-site",
    duration: "4 months",
    category: "unpaid",
    domain: "Research",
    companyType: "ngo",
    verificationStatus: "verified",
    trustScore: 90,
    applicants: 67,
    views: 234,
    postedDate: "1 week ago",
    deadline: "Aug 15, 2026",
    description:
      "Support policy briefs on education, climate, and digital rights. Strong academic writing required.",
    fullDescription:
      "You'll draft 2 policy briefs during the internship, attend parliamentary committee hearings, and present at a public roundtable at the end.",
    skills: ["Academic writing", "Research", "Policy analysis"],
    responsibilities: [
      "Draft 2 policy briefs on assigned topics",
      "Attend committee hearings and write summaries",
      "Present findings at a public roundtable",
    ],
    perks: ["Civic-impact network", "Published byline"],
    eligibility: "Masters / final-year students in policy, law, or economics",
    recruiterEmail: "policy@civicfutures.example",
  },
];

interface CatalogContextValue {
  internships: InternshipData[];
  getById: (id: string) => InternshipData | undefined;
}

const CatalogContext = createContext<CatalogContextValue | undefined>(undefined);

export const CatalogProvider = ({ children }: { children: ReactNode }) => {
  const value = useMemo<CatalogContextValue>(
    () => ({
      internships: INTERNSHIPS_CATALOG,
      getById: (id) => INTERNSHIPS_CATALOG.find((i) => i.id === id),
    }),
    [],
  );

  return <CatalogContext.Provider value={value}>{children}</CatalogContext.Provider>;
};

export const useInternshipCatalog = () => {
  const ctx = useContext(CatalogContext);
  if (!ctx) throw new Error("useInternshipCatalog must be used within a CatalogProvider");
  return ctx;
};